- acceptor.lisp
Allowing "Connection: keep-alive" doesn't really work with 
single-threaded Hunchentoot (eg. on the Raspberry), because
while the server process waits on one TCP connection the browser
tries to open some more to fetch other resources.
> "Connection: close" on unthreaded builds

- misc.lisp
Currently, while serving static files (.html, .css etc) Hunchentoot does not add the "charset" property (e.g. "charset=utf-8") to the Content-Type HTTP header. As the result:
1) When accessing static file via Drakma it does not print UTF-8 characters properly in the REPL (even if static page contains &lt;meta charset="utf-8"&gt;.);
2) It forces to add &lt;meta charset="utf-8"&gt; explicitly in each static HTML file to inform the browsers about encoding. (And if the page does not contains "meta" tag the user will see "abracadabra" instead of the text.)
> While serving static files (.html, .css etc) add "charset" property to Content-Type HTTP header

- acceptor.lisp
Using lexical environment of the with-accessors macro to work with acceptor's slots.
> Bugfix: using variables within with-accessors

- doc/index.xml
- packages.lisp
- session.lisp
- www/hunchentoot-doc.html
Follows up #95 
Open for discussion:
1. function vs method: should this be override-able?
2. The technical limitation of once-per-second.
Revising the 2nd point to remove this limitation would mean going through a randomizer, and if done here, should be done at the existing `initialize-instance` method too, to remain consistent. Another solution would be to use `sb-ext:get-time-of-day` when available? The session id is not changed, so this should be precise enough.
Cheers,
Florian
> Adds the session-regenerate-cookie-value function

- test/script.lisp
Related to #101 and #103
These tests shows that solution with &optional do not cover all cases. Now parse-integer fails.
Regular expression in #102 checked for digits only in that part also.
> test session cookie validation

- easy-handlers.lisp
- misc.lisp
- request.lisp
This fixes the issue, that the server did not return the correct handler if the uri contained characters that need url encoding.
> Decode URL considering content-type's charset

- request.lisp
The parameter names also can be encoded in the external-format.
> In parse-rfc2388-form-data, call convert-hack function also in name

- doc/index.xml
- www/hunchentoot-doc.html
Without this change I get this error:
```
$ cd doc && make
xsltproc --stringparam library-version `perl -ne 'print "$1\n" if (/:version "(.*)"/)' ../hunchentoot.asd` clixdoc.xsl index.xml > ../www/hunchentoot-doc.html
element a: validity error : ID start already defined
$ xsltproc --version
Using libxml 20902, libxslt 10128 and libexslt 817
xsltproc was compiled against libxml 20902, libxslt 10128 and libexslt 817
libxslt 10128 was compiled against libxml 20902
libexslt 817 was compiled against libxml 20902
```
If you'd prefer a less silly name for the anchor just say the word.
> [doc] fix ID clash in index.xml

- doc/index.xml
(For posterity, title was: "fix handler func in CREATE-STATIC-FILE-DISPATCHER-AND-HANDLER")
Fixes the generated handler function to take a `request` argument within the function `create-static-file-dispatcher-and-handler`. This bug caused function application errors within Hunchentoot, stating 1 argument was given but 0 expected. Handler functions should take a single `request` argument to further handle the request.
> Clarify documentation on handler functions

- acceptor.lisp
- specials.lisp
- taskmaster.lisp
This commit avoids the slow busy wait that enables clean shutdown. It
does this by dialing into the acceptor just after ACCEPTOR-SHUTDOWN-P
has been set to true, waking the accept loop so it can check for
shutdown.
The change makes my tests pass in 0 seconds. It also ensures that
the accept loop doesn't wake up every 2s, conserving precious power for
hunchentoot-powered websites that nobody ever visits.
I haven't tested this with the non-threaded taskmaster yet.
> Speed up shutdown and avoid timeout on the listening socket

- hunchentoot.asd
So that `asdf:system-license` can be used.
Thanks a lot!
> Mention license in ASDF, too

- docs/index.html
- docs/index.xml
- www/hunchentoot-doc.html
This is just an idea, not sure whether that's needed; we just get a bit more consistency.
> Documentation: use current package HUNCHENTOOT instead of old TBNL

- docs/index.html
- www/hunchentoot-doc.html
Hi,
Restas was lonely, I added some friends.
fixed Weblock's url to the active fork,
hunchentoot-test example was missing cl-who,
small typo.
I'm confused about `www/hunchentoot-doc.html` and `doc/index.html` though, why are both version controlled ?
Regards
> Doc: add frameworks, typos

- docs/index.html
- docs/index.xml
from `acceptor.lisp`
STARTED-P 
```
Tells if ACCEPTOR has been started.                                                                                                                                               
The default implementation simply queries ACCEPTOR for its listening                                                                                                                                 
status, so if T is returned to the calling thread, then some thread                                                                                                                                  
has called START or some thread's call to STOP hasn't finished. If NIL …
```
> Add in documentation for HUNCHENTOOT:STARTED-P

- set-timeouts.lisp
hunchentoot works fine in clasp, just the timeouts are not yet implemented. Just emit a warning until timeouts are implemented
> Don't error - warn - on timeouts for clasp

- CHANGELOG
- docs/index.xml
- misc.lisp
- packages.lisp
- request.lisp
- ssl.lisp
- www/hunchentoot-doc.html
> Three updates for HT.

- docs/index.xml
`DETACH-SOCKET` returns `NIL`, not the socket stream as might have been implied by the documented function signature.
> Clarify documentation for DETACH-SOCKET

- acceptor.lisp
- ssl.lisp
The default value for backlog (at least in Lispworks 7) is 5, which is pretty low for any practical purpose.
> Support backlog for Lispworks 7

- request.lisp
This trivial change allow Hunchentoot to be compatible with Allegro CL Modern mode (and a lower-case **t** is used through the rest of the code base anyway).
> Change the symbol T to lower case

- request.lisp
In default method for `handler-request'
```
(throw 'handler-done
(values nil cond (get-backtrace)))
```
is used, which is caught in `process-request' and the second return
value is used as error flag. However if handler-request returns
multiple values normally from user code, this also registers as
error.
For example, a define-easy-handler such as
```
(define-easy-handler (...) ()
...
(gethash key table))
```
seems OK as user code. But the `gethash' returns T as second value
which undesirably leads to error.
> discard multiple values returned by handle-request

- cookie.lisp
this allows to set the `SameSite` attribute for a cookie, as explained in more details at
- https://datatracker.ietf.org/doc/html/draft-ietf-httpbis-rfc6265bis-02#section-5.3.7
- https://developer.mozilla.org/en-US/docs/Web/HTTP/Headers/Set-Cookie (Cmd-F "SameSite").
> add SameSite cookie attribute

- acceptor.lisp
- test/script-engine.lisp
- test/script.lisp
This should fix the issue in #138. I don't know that it's a _good_ fix, but it seems to do the right thing. It should support IPv6 addresses as well, although IPv6 support in usocket is still partial.
Suggestions welcome.
> Fix shutdown acceptor wake when listening on 0.0.0.0.

- acceptor.lisp
for https://github.com/edicl/hunchentoot/issues/112
While Google exists, this setting is required and not documented, so this PR could save a couple hours to future developers.
> Document *SHOW-LISP-ERRORS-P* required for custom error template directory

- hunchentoot.asd
- run-test.lisp
I've tested that it behaves the way I expect on my SBCL-macos-arm64 system, but I don't have access to Lispworks, Windows, or a bunch of other combinations, so I'd greatly appreciate sanity checks from anyone who does before I merge.
> rewrite system definitions for simplicity, style and to avoid warnings

- easy-handlers.lisp
The ACCEPTOR-DISPATCH-REQUEST returns the values resulting from a call to CALL-NEXT-METHOD, to ensure EASY-ACCEPTOR is composable with other acceptors, implementing other ACCEPTOR-DISPATCH-REQUEST methods.  The value returned is important to PROCESS-REQUEST which uses it to determine if the handler used by ACCEPTOR-DISPATCH-REQUEST prepared an in-memory version of the answer or wrote it in the appropriate output stream.
In the previous version of the ACCEPTOR-DISPATCH-REQUEST method for EASY-ACCEPTORS, the values
resulting from a call to CALL-NEXT-METHOD are not not transferred to the caller.
> Ensure that an EASY-ACCEPTOR is composable with other acceptors

- ssl.lisp
This implementation now manually creates a ssl-ctx-pointer via `comm:make-ssl-ctx` and configures the certificate and private key on it, which is then attached to the stream.
Previously, `attach-ssl` was called with a symbol parameter for `ssl-ctx` and a callback function. But the callback function was not called.
> Fixed attaching ssl-ctx to stream for Lispworks (8).

- packages.lisp
The special variable `*handle-http-errors-p*` has been removed for a long time now, maybe we can remove the symbol from the package declaration. This may break some user code.
> Remove exported but unused symbol
